# YOUR NAME OR TITLE OF YOUR SITE
name: juvelim

# YOUR BRAND/PERSONAL TAGLINE
tagline: Juventud de Iglesia de Cristo Elim Central



# YOUR/BRAND IMAGE URL
Image_URL: https://images.unsplash.com/photo-1632171962729-ae5999222681?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1604&q=80

# CHANGE THE BACKGROUND IMAGE OF THE WEBSITE BY JUST ADDING THE IMAGE URL
Cover_Image: https://source.unsplash.com/featured/?worship

  #https://source.unsplash.com/random

# SOCIAL MEDIA
links:

  # IF YOU DON'T WANT TO USE ANY OF THE FOLLOWING, JUST LEAVE THE URL BLANK

    # FACEBOOK
  - Name: Facebook
    URL: https://www.facebook.com
    Username: JUVELIMGuatemala
    Color: '#3b5998'
    Icon-Class: fab fa-facebook

    # INSTAGRAM
  - Name: Instagram
    URL: https://www.instagram.com
    Username: juvelim_guate
    Color: '#DD2A7B'
    Icon-Class: fab fa-instagram


    # YOUTUBE
  - Name: YouTube
    URL: https://www.youtube.com/c
    Username: Radio760AMElimCentral
    Color: '#ff0000'
    Icon-Class: fab fa-youtube

    # EMAIL
  - Name: Envíanos un correo
    URL: 'mailto:juvelimguatemala@elimcentral.org'
    Icon-Class: fas fa-envelope
    Color: '#e17055'
    Text_Color: '#ffffff'


    # MESSENGER
  - Name: Comunicate vía Messenger
    URL: https://m.me
    Username: JUVELIMGuatemala
    Color: '#006AFF'
    Icon-Class: fab fa-facebook-messenger


  #   # WHATSAPP
  # - Name: WhatsApp
  #   URL: https://wa.me
  #   Username: '+1123456789'
  #   Color: '#25d366'
  #   Icon-Class: fab fa-whatsapp



    # SPOTIFY
  - Name: Spotify
    URL: https://open.spotify.com/artist
    Username: 5VHQgdumqij6OuSNFDPOn8
    Color: '#1DB954'
    Icon-Class: fab fa-spotify

  #   # SOUNDCLOUD
  # - Name: SoundCloud
  #   URL: https://www.soundcloud.com
  #   Username: harsh98trivedi
  #   Color: '#FE5000'
  #   Icon-Class: fab fa-soundcloud

  #    # TIKTOK
  # - Name: TikTok
  #   URL: https://www.tiktok.com
  #   Username:
  #   Color: '#FE2C55'
  #   Icon-Class: fab fa-tiktok

    # MEDIUM
  # - Name: Medium
  #   URL: 'https://medium.com'
  #   Username: '@harsh98trivedi'
  #   Icon-Class: fab fa-medium-m
  #   Color: '#00ab6c'
  #   Text_Color: '#ffffff'

  #   # DEV.TO
  # - Name: Dev.to
  #   URL: 'https://dev.to'
  #   Username: harsh98trivedi
  #   Icon-Class: fab fa-dev
  #   Color: '#ffffff'
  #   Text_Color: '#000000'

  #   # TUMBLR
  # - Name: Tumblr
  #   URL: https://www.tumblr.com
  #   Username:
  #   Color: '#35465c'
  #   Icon-Class: fab fa-tumblr

    # CUSTOM LINK
  # - Name: Blog
  #   URL: https://harsh98trivedi.github.io/blog
  #   Icon-Class: fas fa-link
  #   Color: '#ffb142'
  #   Text_Color: '#ffffff'

  # - Name: Links
  #   URL: https://github.com/harsh98trivedi/links
  #   Icon-Class: fas fa-link
  #   Color: '#d94869'
  #   Text_Color: '#ffffff'

# YOU CAN REMOVE FOOTER COMPLETELY BY SIMPLY REMOVING EITHER THE YES OR REMOVING THE FOOTER STATEMENT BELOW COMPLETELY
footer: 'Yes'

# STOP EDITING HERE ---------- YOU'VE REACHED THE END OF THE CONFIGURATION

# Compress
compress_html:
  clippings: all

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Icon

# Base URL
baseurl: /links

# Default Markdown Engine
markdown: kramdown

url: https://github.com/jmarcos-cano/links.git
